#!/bin/bash
# Creado por Alvaro Araya O. coder at aao.cr
clear
echo " ____    ____ ________ ____  _____ _____  _____  ";
echo "|_   \  /   _|_   __  |_   \|_   _|_   _||_   _| ";
echo "  |   \/   |   | |_ \_| |   \ | |   | |    | |   ";
echo "  | |\  /| |   |  _| _  | |\ \| |   | '    ' |   ";
echo " _| |_\/_| |_ _| |__/ |_| |_\   |_   \ \__/ /    ";
echo "|_____||_____|________|_____|\____|   \`.__.'     ";
echo "                                                 ";

echo " "

PS3='Opt: '
COLUMNS=125
options=(
    "opcion1"
    "opcion2"
    "opcion3"
    "exit");

execOption () {
  echo "Ejecutando: $1"
  case $1 in
      "opcion1") 		echo "Opcion1 - sustituir por los comandos, mantener ;; al final";;
      "opcion2") 		echo "Opcion2 - sustituir por los comandos, mantener ;; al final";;
      "opcion3") 		echo "Opcion3 - sustituir por los comandos, mantener ;; al final";;
      "exit")				;;
      *) echo invalid option;;
  esac
}

if [ -n "$1" ]; then
  # si el número es especificado como argumento no muestra el case
  execOption ${options[$(($1-1))]}
else
  select opt in "${options[@]}"
  do
    execOption $opt
    break
  done
fi